import java.awt.Font;
/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Quarantine Qangaroo");

  // Title and prompt
  title = new GLabel(this, 0, 20, 960, 100);
  title.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  title.setText("Quarantine Qangaroo");
  title.setFont(new Font("Dialog", Font.PLAIN, 60));
  title.setOpaque(false);
  
  prompt = new GLabel(this, 0, 120, 960, 80);
  prompt.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  prompt.setText("Push Button to Play!");
  prompt.setFont(new Font("Dialog", Font.PLAIN, 36));
  
  // High score area
  highScoreLabel = new GLabel(this, 330, 500, 200, 120);
  highScoreLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  highScoreLabel.setText("High Score:");
  highScoreLabel.setFont(new Font("Dialog", Font.PLAIN, 32));
  highScoreLabel.setOpaque(false);
  
  highScore = new GLabel(this, 530, 500, 50, 120);
  highScore.setTextAlign(GAlign.CENTER, GAlign.LEFT);
  highScore.setFont(new Font("Dialog", Font.PLAIN, 32));
  highScore.setText("0");
  highScore.setOpaque(false);
  
  // Player 1 Scoreboard
  label1 = new GLabel(this, 140, 410, 240, 60);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setFont(new Font("Dialog", Font.PLAIN, 48));
  label1.setText("Player 1");
  label1.setOpaque(false);
  
  score1 = new GLabel(this, 140, 130, 240, 300);
  score1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  score1.setFont(new Font("Dialog", Font.PLAIN, 120));
  score1.setText("0");
  score1.setOpaque(false);
  
  // Player 2 Scoreboard
  label2 = new GLabel(this, 570, 410, 240, 60);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setFont(new Font("Dialog", Font.PLAIN, 48));
  label2.setText("Player 2");
  label2.setOpaque(false);
  
  score2 = new GLabel(this, 570, 130, 240, 300);
  score2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  score2.setFont(new Font("Dialog", Font.PLAIN, 120));
  score2.setText("0");
  score2.setOpaque(false);
  
  // Countdown
  countdown = new GLabel(this, 380, 130, 190, 300);
  countdown.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  countdown.setFont(new Font("Dialog", Font.PLAIN, 100));
  countdown.setText("");
  countdown.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GLabel label1; 
GLabel label2; 
GLabel title;
GLabel prompt;
GLabel highScoreLabel; 
GLabel highScore; 
GLabel score1; 
GLabel score2; 
GLabel countdown;
